const { Partner } = require('../models/Partner');
const { ServiceListing, PropertyListing, MandiListing } = require('../models/Listing');
const { Enquiry } = require('../models/Enquiry');
const { SubscriptionPlan } = require('../models/Finance');

/**
 * @desc    Submit KYC and onboard a partner
 * @route   POST /api/partners/onboard
 * @access  Private (Partner Token Required)
 */
const onboardPartner = async (req, res) => {
  try {
    // req.user comes from our 'protect' middleware
    // We already ensure the user has a valid JWT token.
    const partnerId = req.user.id;

    // Destructure everything we expect from the frontend request body
    const { 
      name, email, partner_type, 
      id_type, id_number, id_front_url, id_back_url,
      // Profile data:
      category_id, rera_number, rera_certificate_image, agency_name,
      material_categories, delivery_radius_km
    } = req.body;

    // 1. Find the partner document. (It was created as a blank skeleton during verifyOtp)
    const partner = await Partner.findById(partnerId);

    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner account not found' });
    }

    if (partner.onboarding_status === 'approved') {
      return res.status(400).json({ success: false, message: 'Already approved. Edit profile instead.' });
    }

    // 2. Update their basic info
    partner.name = name || partner.name;
    partner.email = email || partner.email;
    partner.partner_type = partner_type || partner.partner_type;

    // 3. Attach KYC documentation URLs (these URLs will have been generated by our Cloudinary /upload endpoint)
    partner.kyc = {
      status: 'pending', // Re-trigger manual admin review
      id_type,
      id_number,
      id_front_url,
      id_back_url
    };

    // 4. Update the flexible profile based on their type
    // If they are a service provider, we put the data in `service_profile`
    if (partner.partner_type === 'service_provider') {
      partner.profile.service_profile = { category_id };
    } 
    else if (partner.partner_type === 'property_agent') {
      partner.profile.property_profile = { rera_number, rera_certificate_image, agency_name };
    }
    else if (partner.partner_type === 'supplier') {
      partner.profile.supplier_profile = { material_categories, delivery_radius_km };
    }

    // 5. Change their overall status to pending admin approval!
    partner.onboarding_status = 'pending_approval';

    // Save to MongoDB
    await partner.save();

    res.status(200).json({
      success: true,
      message: 'Onboarding submitted! Please wait for Admin approval.',
      data: partner
    });

  } catch (error) {
    console.error("Error in onboardPartner:", error);
    res.status(500).json({ success: false, message: 'Server error during onboarding.' });
  }
};

/**
 * @desc    Get the partner's own profile
 * @route   GET /api/partners/profile
 * @access  Private (Partner Token Required)
 */
const getMyPartnerProfile = async (req, res) => {
  try {
    const partnerId = req.user.id;
    
    // Fetch the partner from the database
    // .populate() automatically fetches related data if we ref another collection
    const partner = await Partner.findById(partnerId)
      .populate('active_subscription_id');

    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner not found' });
    }

    res.status(200).json({
      success: true,
      data: partner
    });

  } catch (error) {
    console.error("Error in getMyPartnerProfile:", error);
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

/**
 * @desc    Get dashboard stats for partner
 * @route   GET /api/partners/stats
 * @access  Private (Partner Token Required)
 */
const getPartnerStats = async (req, res) => {
  try {
    const partnerId = req.user._id;

    // 1. Get Listing Stats
    const modelMap = {
      'property_agent': PropertyListing,
      'service_provider': ServiceListing,
      'supplier': null // Suppliers no longer have individual listings to track stats for
    };

    const partner = await Partner.findById(partnerId);
    if (!partner) return res.status(404).json({ success: false, message: 'Partner not found' });

    const ListingModel = modelMap[partner.active_role || partner.partner_type] || PropertyListing;

    let total = 0, active = 0, pending = 0, featured = 0;
    if (ListingModel) {
      const stats = await Promise.all([
        ListingModel.countDocuments({ partner_id: partnerId }),
        ListingModel.countDocuments({ partner_id: partnerId, status: 'active' }),
        ListingModel.countDocuments({ partner_id: partnerId, status: 'pending_approval' }),
        ListingModel.countDocuments({ partner_id: partnerId, is_featured: true })
      ]);
      [total, active, pending, featured] = stats;
    }

    // 2. Get Inquiry/Leads Stats
    const [totalLeads, unreadLeads] = await Promise.all([
      Enquiry.countDocuments({ partner_id: partnerId }),
      Enquiry.countDocuments({ partner_id: partnerId, is_read: false })
    ]);

    res.status(200).json({
      success: true,
      data: {
        listings: { total, active, pending, featured },
        leads: { total: totalLeads, unread: unreadLeads }
      }
    });

  } catch (error) {
    console.error("Error fetching partner stats:", error);
    res.status(500).json({ success: false, message: 'Error fetching dashboard stats.' });
  }
};

/**
 * @desc    Add a new role to an existing partner account
 * @route   POST /api/partners/add-role
 * @access  Private (Partner Token Required)
 */
const addRole = async (req, res) => {
  try {
    const partnerId = req.user.id;
    const { new_role, profile_data, gst_number, gst_image, rera_number, rera_certificate_image } = req.body;

    const validRoles = ['service_provider', 'property_agent', 'supplier', 'mandi_seller'];
    if (!new_role || !validRoles.includes(new_role)) {
      return res.status(400).json({ success: false, message: 'Invalid role specified.' });
    }

    const partner = await Partner.findById(partnerId);
    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner account not found.' });
    }

    // Check if the role is already active
    const activeRoles = partner.roles || (partner.partner_type ? [partner.partner_type] : []);
    if (activeRoles.includes(new_role)) {
      return res.status(400).json({ success: false, message: 'You already have this role active.' });
    }

    // Check if there's already a pending request for this role
    const existingRequest = partner.role_requests?.find(r => r.role === new_role && r.status === 'pending');
    if (existingRequest) {
      return res.status(400).json({ success: false, message: 'A request for this role is already pending approval.' });
    }

    // Roles requiring GST validation
    const gstRequiredRoles = ['supplier', 'mandi_seller'];
    if (gstRequiredRoles.includes(new_role)) {
      if (!gst_number || !gst_image) {
        return res.status(400).json({ success: false, message: 'GST details and certificate image are required for this role.' });
      }
    }

    // Add to role_requests as ALL role upgrades now require admin approval
    if (!partner.role_requests) partner.role_requests = [];
    partner.role_requests.push({
      role: new_role,
      status: 'pending',
      gst_number: gst_number || undefined,
      gst_image: gst_image || undefined,
      rera_number: rera_number || undefined,
      rera_certificate_image: rera_certificate_image || undefined,
      submitted_at: new Date()
    });

    // Remove from deleted_roles if it was there to allow fresh re-application
    if (partner.deleted_roles) {
      partner.deleted_roles = partner.deleted_roles.filter(r => r !== new_role);
    }

    // Temporarily save profile data; it will become active once approved
    if (profile_data) {
      if (new_role === 'supplier') {
        partner.profile.supplier_profile = { ...(partner.profile.supplier_profile || {}), ...profile_data };
      } else if (new_role === 'mandi_seller') {
        partner.profile.mandi_profile = { ...(partner.profile.mandi_profile || {}), ...profile_data };
      } else if (new_role === 'property_agent') {
        partner.profile.property_profile = { ...(partner.profile.property_profile || {}), ...profile_data };
      } else if (new_role === 'service_provider') {
        partner.profile.service_profile = { ...(partner.profile.service_profile || {}), ...profile_data };
      }
    }

    await partner.save();

    return res.status(200).json({
      success: true,
      message: `Request for "${new_role.replace('_', ' ')}" submitted for admin approval.`,
      data: {
        role_requests: partner.role_requests,
        status: 'pending'
      }
    });

  } catch (error) {
    console.error("Error in addRole:", error);
    res.status(500).json({ success: false, message: 'Server error adding role.' });
  }
};

/**
 * @desc    Delete a role from partner account
 * @route   DELETE /api/partners/delete-role
 * @access  Private (Partner Token Required)
 */
const deleteRole = async (req, res) => {
  try {
    const partnerId = req.user.id;
    const { role } = req.body;

    if (!role) {
      return res.status(400).json({ success: false, message: 'Role not specified.' });
    }

    const partner = await Partner.findById(partnerId);
    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner not found.' });
    }

    // Cannot delete the only active role
    if (partner.roles.length <= 1) {
      return res.status(400).json({ success: false, message: 'Cannot delete your only active role.' });
    }

    if (!partner.roles.includes(role)) {
      return res.status(400).json({ success: false, message: 'Role is not active.' });
    }

    // Remove from roles
    partner.roles = partner.roles.filter(r => r !== role);

    // Add to deleted_roles
    if (!partner.deleted_roles) partner.deleted_roles = [];
    if (!partner.deleted_roles.includes(role)) {
      partner.deleted_roles.push(role);
    }

    // If deleting active role, switch to another
    if (partner.active_role === role) {
      partner.active_role = partner.roles[0];
      partner.partner_type = partner.roles[0];
    }

    await partner.save();

    res.status(200).json({
      success: true,
      message: `Role "${role}" deleted successfully.`,
      data: {
        roles: partner.roles,
        active_role: partner.active_role
      }
    });

  } catch (error) {
    console.error("Error in deleteRole:", error);
    res.status(500).json({ success: false, message: 'Server error deleting role.' });
  }
};

/**
 * @desc    Switch the active role for the partner dashboard
 * @route   PUT /api/partners/switch-role
 * @access  Private (Partner Token Required)
 */
const switchRole = async (req, res) => {
  try {
    const partnerId = req.user.id;
    const { role } = req.body;

    const partner = await Partner.findById(partnerId);
    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner not found.' });
    }

    // Validate the partner has this role
    const partnerRoles = partner.roles && partner.roles.length > 0 
      ? partner.roles 
      : (partner.partner_type ? [partner.partner_type] : []);

    if (!partnerRoles.includes(role)) {
      return res.status(403).json({ success: false, message: 'You do not have this role.' });
    }

    partner.active_role = role;
    partner.partner_type = role; // Keep legacy field in sync
    await partner.save();

    res.status(200).json({
      success: true,
      message: `Switched to ${role} view.`,
      data: {
        active_role: partner.active_role,
        partner_type: partner.partner_type,
        roles: partner.roles
      }
    });

  } catch (error) {
    console.error("Error in switchRole:", error);
    res.status(500).json({ success: false, message: 'Server error switching role.' });
  }
};

/**
 * @desc    Get public partner profiles for discovery
 * @route   GET /api/partners/public
 * @access  Public
 */
const getPublicPartners = async (req, res) => {
  try {
    const { category, search, district, state, is_featured } = req.query;

    const query = process.env.NODE_ENV === 'development'
      ? { is_active: { $in: [true, false] }, onboarding_status: { $in: ['approved', 'pending_approval', 'incomplete'] } }
      : { is_active: true, onboarding_status: 'approved' };

    if (is_featured === 'true') {
      query.is_featured = true;
    }

    // Filter by role/type
    if (category) {
      // If we are looking for suppliers, check both roles array and partner_type
      query.$or = [
        { roles: category },
        { partner_type: category }
      ];
    }

    // Filter by location (Skipped in development to show all data)
    if (process.env.NODE_ENV !== 'development') {
      if (district) query.district = new RegExp(district, 'i');
      if (state) query.state = new RegExp(state, 'i');
    }

    // Search by name or business name
    if (search) {
      const searchRegex = new RegExp(search, 'i');
      query.$or = [
        ...(query.$or || []),
        { name: searchRegex },
        { 'profile.supplier_profile.business_name': searchRegex },
        { 'profile.mandi_profile.business_name': searchRegex }
      ];
    }

    const partners = await Partner.find(query)
      .populate('profile.service_profile.category_id')
      .limit(50);

    res.status(200).json({
      success: true,
      data: partners
    });
  } catch (error) {
    console.error("Error fetching public partners:", error);
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

/**
 * @desc    Get a single public partner profile
 * @route   GET /api/partners/public/:id
 * @access  Public
 */
const getPublicPartnerById = async (req, res) => {
  try {
    const partner = await Partner.findById(req.params.id);
    if (!partner || !partner.is_active) {
      return res.status(404).json({ success: false, message: 'Partner not found' });
    }

    res.status(200).json({
      success: true,
      data: partner
    });
  } catch (error) {
    console.error("Error fetching public partner by id:", error);
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

/**
 * @desc    Get all active subscription plans for partners
 * @route   GET /api/partners/subscriptions/plans
 * @access  Private (Partner)
 */
const getPartnerSubscriptionPlans = async (req, res) => {
  try {
    const plans = await SubscriptionPlan.find({ is_active: true }).sort({ price: 1 });
    res.status(200).json({ success: true, count: plans.length, data: plans });
  } catch (error) {
    console.error("Error fetching subscription plans:", error);
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

/**
 * @desc    Toggle partner featured status
 * @route   PUT /api/partners/toggle-feature
 * @access  Private (Partner)
 */
const toggleFeature = async (req, res) => {
  try {
    const partnerId = req.user.id;
    const partner = await Partner.findById(partnerId);
    
    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner not found' });
    }

    // Toggle featured status
    partner.is_featured = !partner.is_featured;
    await partner.save();

    res.status(200).json({
      success: true,
      message: partner.is_featured ? 'You are now featured!' : 'Feature disabled.',
      is_featured: partner.is_featured
    });
  } catch (error) {
    console.error("Error toggling feature:", error);
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

module.exports = {
  onboardPartner,
  getMyPartnerProfile,
  getPartnerStats,
  addRole,
  switchRole,
  deleteRole,
  getPublicPartners,
  getPublicPartnerById,
  getPartnerSubscriptionPlans,
  toggleFeature
};
