const { Partner } = require('../models/Partner');

/**
 * @desc    Submit KYC and onboard a partner
 * @route   POST /api/partners/onboard
 * @access  Private (Partner Token Required)
 */
const onboardPartner = async (req, res) => {
  try {
    // req.user comes from our 'protect' middleware
    // We already ensure the user has a valid JWT token.
    const partnerId = req.user.id;

    // Destructure everything we expect from the frontend request body
    const { 
      name, email, partner_type, 
      id_type, id_number, id_front_url, id_back_url,
      // Profile data:
      category_id, rera_number, agency_name,
      material_categories, delivery_radius_km
    } = req.body;

    // 1. Find the partner document. (It was created as a blank skeleton during verifyOtp)
    const partner = await Partner.findById(partnerId);

    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner account not found' });
    }

    if (partner.onboarding_status === 'approved') {
      return res.status(400).json({ success: false, message: 'Already approved. Edit profile instead.' });
    }

    // 2. Update their basic info
    partner.name = name || partner.name;
    partner.email = email || partner.email;
    partner.partner_type = partner_type || partner.partner_type;

    // 3. Attach KYC documentation URLs (these URLs will have been generated by our Cloudinary /upload endpoint)
    partner.kyc = {
      status: 'pending', // Re-trigger manual admin review
      id_type,
      id_number,
      id_front_url,
      id_back_url
    };

    // 4. Update the flexible profile based on their type
    // If they are a service provider, we put the data in `service_profile`
    if (partner.partner_type === 'service_provider') {
      partner.profile.service_profile = { category_id };
    } 
    else if (partner.partner_type === 'property_agent') {
      partner.profile.property_profile = { rera_number, agency_name };
    }
    else if (partner.partner_type === 'supplier') {
      partner.profile.supplier_profile = { material_categories, delivery_radius_km };
    }

    // 5. Change their overall status to pending admin approval!
    partner.onboarding_status = 'pending_approval';

    // Save to MongoDB
    await partner.save();

    res.status(200).json({
      success: true,
      message: 'Onboarding submitted! Please wait for Admin approval.',
      data: partner
    });

  } catch (error) {
    console.error("Error in onboardPartner:", error);
    res.status(500).json({ success: false, message: 'Server error during onboarding.' });
  }
};

/**
 * @desc    Get the partner's own profile
 * @route   GET /api/partners/profile
 * @access  Private (Partner Token Required)
 */
const getMyPartnerProfile = async (req, res) => {
  try {
    const partnerId = req.user.id;
    
    // Fetch the partner from the database
    // .populate() automatically fetches related data if we ref another collection
    const partner = await Partner.findById(partnerId)
      .populate('active_subscription_id');

    if (!partner) {
      return res.status(404).json({ success: false, message: 'Partner not found' });
    }

    res.status(200).json({
      success: true,
      data: partner
    });

  } catch (error) {
    console.error("Error in getMyPartnerProfile:", error);
    res.status(500).json({ success: false, message: 'Server Error' });
  }
};

module.exports = {
  onboardPartner,
  getMyPartnerProfile
};
